version: "3.8"

services:
  database:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass

volumes:
  database-data:
